### ISSUE TITLE
Merge with es6-collections

### ISSUE THREAD

**Issue by adius** [Steditor/es6-collections-iterators#1]
Why is this a separate repo? Shouldn't it be merged with https://github.com/WebReflection/es6-collections?

**Comment by Steditor** [comment]
No, it shouldn't imho.
es6-collections provides a full polyfill, that already includes the methods this repo adds - but it works on a totally different datastructure. Due to the fact that IE implements the collections itself, but only partly, the full polyfill can't (or better: shouldn't as far as I feel about the topic) be applied and therefore this polyfill deals with adding the specific missing methods.

**Comment by adius** [comment]
Sounds reasonable. …but it's really messy that we have to fix around the broken implementations. =(
